loopbackio/loopback-ibmdb

lib/ibmdb.js

`toColumnValue()` should treat undefined.
This fixes all of the test cases for `loopback-connector-db2` for `replaceById`(atomic) and `replaceOrCreate` (non-atomic).
to:/ @qpresley PTAL. Thanks!

`toColumnValue()` should treat undefined.

---

lib/ibmdb.js

Avoid update all instances when using save/updateOrCreate
Connect to https://github.com/strongloop/loopback-connector-db2/issues/38
Please review: @loay @superkhau @jannyHou 
CC: @bajtos @qpresley

Avoid update all in save and updateOrCreate

---

lib/ibmdb.js

There will be a number of changes eventually go into the underlying node-ibm_db module which would break the current implementation.  By making these changes the code will be resilient to the changes in the underlying layer.

Stability fixes

---

lib/ibmdb.js
package.json

There was some work left out in a previous PR where we now use pooled connections properly in DB2 and other IBM connectors.  The piece that was left out was closing the connection once finished with it if we are not in a transaction.  This PR will add that which closes a hole where we are currently leaking connections.
@Amir-61 @superkhau  PTAL

Need to close connections to return to pool

---

lib/ibmdb.js

@rmg, this PR should address #17 PTAL.
Fix is pretty simple.  Add conn.close(function() {}); to two additional locations inside the transaction block.

Ensure connection close on failure

---

lib/ibmdb.js

Initial PR for adding connection pooling settings which will soon be supported in a node-ibm_db release.

Add initial settings config

---

lib/ibmdb.js

Lazy connect does not hold meaning in the IBM Database connectors.  On initialization there is no connection acquired for the connector.  If the user specifies a min or max connection pool size in the settings past in on initialization then the underlying connection pool in the node-ibm_db module will have connections ready.

remove connect/lazyconnect

---

package.json

node-ibmdb has released a new version which contains many updates that customers are already relying on and are required for updates to the informix connector.  This PR just increases to the 2.0.0 stream.

Update ibm_db minimum version

---

package.json

Update dependency version of loopback-connector to 3.x
Now CI test of db2 connectors cannot pick the latest code in loopback-connector@master, because `loopback-ibmdb` is still using `loopback-connector@2.x`
And dropping node@0.10, 0.12 support as well.

Upgrade to loopback-connector@3.x

---

lib/ibmdb.js

connect to https://github.com/strongloop-internal/scrum-apex/issues/110
Fix replaceById bug when id does not exist in db. 
Test cases are in juggler.

Fix replaceById bug when id not found

---

lib/ibmdb.js

Adding the setConnectionProperties prototype to allow the connection settings to differ for each IBM connector.  For example, DB2 allows the use of "CurrentSchema" in the DSN but doesn't allow for "AUTHENTICATION=SERVER" while Informix does not allow "CurrentSchema" but requires "AUTHENTICATION=SERVER"

Set connection properties

---

lib/ibmdb.js

This code adds the _replace function for the IBM connectors and fixes up some issues with the replaceOrCreate function.  It also contains a few minor typo's and removal of dead code.

Replace discovery migration

---

lib/migration.js

The autoupdate logic was initially built for DB2 only and relied on system catalogs that do not apply to all databases in the IBM set.  These changes will make the autoupdate function much more generic and possibly more functionally correct as it ensures the order of operations will not cause issues such as a column of a table being dropped while an index using that column still exists in the database.
While this may not be the most performant version of autoupdate, this is unlikely to be something users do frequently and the rebuilding of the indexes may improve database performance in some cases.

Make the autoupdate logic much more generic

---

lib/ibmdb.js

Remove debug logging of connection string details.
When a user has debug set for the connector the full connection string would be printed in the debug output.  This runs the risk of exposing login details for the database server and should printed even in the event debugging is enabled.  Note that be default debug is not enabled and users have to explicitly enable it for this printing to occur.

Remove connection string logging

---

lib/ibmdb.js
package.json
test/connect.test.js
test/functional.test.js
test/ibmdb.config.test.js

connected to: https://github.com/strongloop/loopback-ibmdb/issues/51
It gives error when parsing `val` when it's undefined.

fix fromColumnValue when val is undefined

---

lib/migration.js

Add escape function on the column names in add, change and drop operations to allow the underlying database deal with the name escaping.
connect to https://github.com/strongloop/loopback-ibmdb/issues/53

Escape column names on add/change/drop

---

lib/ibmdb.js
lib/migration.js

- Fix `self.columnEscaped()` function params
- Remove duplicate `IBMDB.prototype.escapeName` function
connect to https://github.com/strongloop/loopback-ibmdb/issues/53

Fix columnEscaped params

---

lib/ibmdb.js
lib/migration.js

- Drop primary indexes correctly as part of **alter table**
- Build primary indexes correctly as part of **alter table**
connect to https://github.com/strongloop-internal/scrum-apex/issues/280

Fix build and drop of primary indexes

---

.eslintrc
index.js
lib/globalize.js
lib/ibmdb.js
lib/migration.js
package.json
test/connect.test.js
test/ibmdb.config.test.js
test/init.js
test/require.test.js

Update eslint to v4 and use the `loopback` extension.

Update linter and rules

---

lib/ibmdb.js

Override `buildExpression` function from base sql connector to allow db2/dashdb based regexp syntax.
The function is exactly the same as the one in [base connector](https://github.com/strongloop/loopback-connector/blob/master/lib/sql.js#L978) except the case for regexp in this [line](https://github.com/strongloop/loopback-ibmdb/compare/fix/override-buildExpression?expand=1#diff-4264eb1de5b89690cd7cd0ff815b745bR900)
connect to https://github.com/strongloop/loopback-connector-dashdb/issues/51

Override buildExpression from base connector

---

package.json

The old strong-globalize level of 3.1.0 seems to pull in swagger-client which has a dependency on `kyles-hockey/js-yaml` which fails to install.
Unable to install loopback-ibmdb and hence some connectors on some platforms due to failure to install dependent package

Changing strong-globalize level to 4.1.0

---

package.json

The install issue was not due to strong-globalize version it was due to kyleshockey/js-yaml required npmjs.org login in .npmrc.  If not logged in than this package will not install.  In the 3.1 version of strong-globalize this package is a required dependency, in 4.1 it is not.

Revert change to strong-globalize version

---

lib/ibmdb.js

toColumnValue was only returning the val back to the user in the default type case.  This causes problems with embedded relations as they are defined as a JSON block with no proper type defined in the property.  The toColumnValue should either be able to distinguish the name of a type OR assume that type is a JSON object and return the stringified JSON text.

Fix toColumnValue with proper default

---

lib/ibmdb.js
test/functional.test.js

Today, when using the loopback-connector-db2, milliseconds are handled incorrectly: milliseconds of date objects are stored in timestamps as if they were microseconds (1 ms is stored in DB2 as 1 μs and are lost when you read them back from DB2). This PR contains a new test that will fail without the also included change of dateToIBMDB function in lib/ibmdb.js. The changed code puts milliseconds in the first three digits of the microsecond part of timestamps.
No issue has been created.

Handle ms part of timestamps correctly for DB2

---

package.json

Dropping support for node 6.x.
connect to: https://github.com/strongloop/loopback-ibmdb/issues/79 
[PR #80](https://github.com/strongloop/loopback-ibmdb/pull/80) depends on this  PR.

feat: drop node 6.x support

---

index.js
lib/globalize.js
lib/ibmdb.js
lib/migration.js
test/connect.test.js
test/functional.test.js
test/ibmdb.config.test.js
test/init.js
test/require.test.js

Related to: https://github.com/strongloop-internal/scrum-apex/issues/440
The changes in this PR are generated by running `slt copyright` command.
- connect to <link_to_referenced_issue>

chore: update copyright year

---

lib/ibmdb.js

Relate to : https://github.com/strongloop/loopback-ibmdb/issues/84 
- connect to <link_to_referenced_issue>

fix: during replace, use id column name if specified

---

.github/workflows/continuous-integration.yml
package-lock.json
test/init.js

Fix : ci test pass
